# Datenstrom Yellow extension settings

Extension: SectionEdit
Version: 0.1.27
Description: Edit individual sections of a page.
Developer: Alexander Griehl
Tag: feature
DownloadUrl: https://github.com/Whoopsadaisy/yellow-sectionedit/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/Whoopsadaisy/yellow-sectionedit
DocumentationLanguage: en, de
Published: 2026-09-17 00:00:00
Status: maintained
system/workers/sectionedit.php: sectionedit.php, create, update
