# Datenstrom Yellow extension settings

Extension: SectionEdit
Version: 0.1.23
Description: Edit individual sections of a page.
Developer: Alexander Griehl
Tag: feature
DownloadUrl: https://github.com/Whoopsadaisy/yellow-sectionedit/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/Whoopsadaisy/yellow-sectionedit
DocumentationLanguage: en, de
Published: 2026-09-17 00:00:00
Status: maintained
system/workers/sectionedit.php: sectionedit.php, create, update
system/workers/sectionedit-part1.php: sectionedit-part1.php, create, update
system/workers/sectionedit-part2.php: sectionedit-part2.php, create, update
system/workers/sectionedit-part3.php: sectionedit-part3.php, create, update
system/workers/sectionedit-part4.php: sectionedit-part4.php, create, update
system/workers/sectionedit-part5.php: sectionedit-part5.php, create, update
system/workers/sectionedit-part6.php: sectionedit-part6.php, create, update
