<?php
trait YellowSectioneditPart3 {
function showEditor($edit, $scheme, $address, $base, $location, $fileName, $rawDataSource, $endOfLine) {
        $sectionId = $this->getSectionId(); $sections = $this->scan($rawDataSource); $section = $this->findSection($sections, $sectionId);
        if (!$section) return $this->showSectionDiagnostic($location, $fileName, $sectionId, $sections, $base);
        $sectionText = substr($rawDataSource, $section["start"], $section["end"] - $section["start"]);
        $csrf = $this->yellow->toolbox->getCookie("yellowcsrftoken");
        $actionUrl = $this->yellow->lookup->normaliseUrl($scheme, $address, $this->yellow->system->get("coreServerBase"), rtrim($this->yellow->system->get("sectioneditLocation"), "/") . $location);
        $actionUrl .= (strpos($actionUrl, "?") === false ? "?" : "&") . "action=edit&section=" . rawurlencode($sectionId);
        $cancelUrl = $this->yellow->lookup->normaliseUrl($scheme, $address, $base, $location); $cancelAnchor = $this->getSectionAnchor($rawDataSource, $sectionId);
        if (!is_string_empty($cancelAnchor)) $cancelUrl .= "#" . rawurlencode($cancelAnchor);
        $title = htmlspecialchars($section["title"], ENT_QUOTES, "UTF-8"); $text = htmlspecialchars($sectionText, ENT_QUOTES, "UTF-8"); $source = htmlspecialchars($rawDataSource, ENT_QUOTES, "UTF-8"); $eol = htmlspecialchars($endOfLine, ENT_QUOTES, "UTF-8"); $id = htmlspecialchars($sectionId, ENT_QUOTES, "UTF-8"); $actionUrl = htmlspecialchars($actionUrl, ENT_QUOTES, "UTF-8"); $cancelUrl = htmlspecialchars($cancelUrl, ENT_QUOTES, "UTF-8"); $csrf = htmlspecialchars($csrf, ENT_QUOTES, "UTF-8");
        $assetLocation = $this->yellow->system->get("coreServerBase") . $this->yellow->system->get("coreAssetLocation");
        $html = '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Edit: ' . $title . '</title>';
        $theme = $this->yellow->page->get("theme"); $themeName = $this->yellow->lookup->normaliseName($theme); $themeFile = $this->yellow->system->get("coreThemeDirectory") . $themeName . ".css";
        if (is_file($themeFile)) $html .= '<link rel="stylesheet" type="text/css" media="all" href="' . htmlspecialchars($assetLocation . $themeName . ".css", ENT_QUOTES, "UTF-8") . '" />';
        $html .= '<link rel="stylesheet" type="text/css" media="all" href="' . htmlspecialchars($assetLocation . 'edit.css', ENT_QUOTES, "UTF-8") . '" /><style>' . $this->getCss() . '</style></head><body class="sectionedit-body">';
        $html .= '<main class="sectionedit yellow-pane"><div class="yellow-content"><form method="post" action="' . $actionUrl . '" id="sectionedit-form">';
        $html .= '<input type="hidden" name="action" value="edit"><input type="hidden" name="section" value="' . $id . '"><input type="hidden" name="yellowcsrftoken" value="' . $csrf . '">';
        $html .= '<textarea hidden name="rawdatasource" id="rawdatasource">' . $source . '</textarea><input type="hidden" name="rawdataendofline" value="' . $eol . '">';
        $html .= '<div id="sectionedit-toolbar"><ul class="yellow-toolbar yellow-toolbar-left sectionedit-toolbar-buttons">';
        $html .= '<li><a href="#" class="yellow-toolbar-btn-icon yellow-toolbar-tooltip" data-section-action="format" aria-label="Format"><i class="yellow-icon yellow-icon-format"></i></a></li><li><a href="#" class="yellow-toolbar-btn-icon yellow-toolbar-tooltip" data-section-action="bold" aria-label="Bold"><i class="yellow-icon yellow-icon-bold"></i></a></li><li><a href="#" class="yellow-toolbar-btn-icon yellow-toolbar-tooltip" data-section-action="italic" aria-label="Italic"><i class="yellow-icon yellow-icon-italic"></i></a></li><li><a href="#" class="yellow-toolbar-btn-icon yellow-toolbar-tooltip" data-section-action="strikethrough" aria-label="Strikethrough"><i class="yellow-icon yellow-icon-strikethrough"></i></a></li><li><a href="#" class="yellow-toolbar-btn-icon yellow-toolbar-tooltip" data-section-action="code" aria-label="Code"><i class="yellow-icon yellow-icon-code"></i></a></li><li><a href="#" class="yellow-toolbar-btn-icon yellow-toolbar-tooltip" data-section-action="list" aria-label="List"><i class="yellow-icon yellow-icon-list"></i></a></li><li><a href="#" class="yellow-toolbar-btn-icon yellow-toolbar-tooltip" data-section-action="link" aria-label="Link"><i class="yellow-icon yellow-icon-link"></i></a></li><li><a href="#" class="yellow-toolbar-btn-icon yellow-toolbar-tooltip" data-section-action="preview" aria-label="Preview"><i class="yellow-icon yellow-icon-preview"></i></a></li></ul>';
        $html .= '<ul class="yellow-toolbar yellow-toolbar-right sectionedit-toolbar-main"><li><a href="' . $cancelUrl . '" class="yellow-toolbar-btn">Cancel</a></li><li><a href="#" id="sectionedit-submit" class="yellow-toolbar-btn yellow-toolbar-btn-edit" data-section-action="save">Save</a></li></ul><ul class="yellow-toolbar yellow-toolbar-banner"></ul></div>';
        $html .= '<textarea name="sectiondata" id="sectiondata" class="yellow-edit-text" spellcheck="false">' . $text . '</textarea><div id="sectionedit-preview" class="yellow-edit-preview" hidden></div></form></div></main><script type="text/javascript">';
        $html .= '(function(){var text=document.getElementById("sectiondata"),form=document.getElementById("sectionedit-form"),preview=document.getElementById("sectionedit-preview");';
        $html .= 'function focusText(){text.focus();}function wrap(prefix,suffix){var a=text.selectionStart,b=text.selectionEnd,v=text.value,s=v.slice(a,b);text.focus();text.setSelectionRange(a,b);document.execCommand("insertText",false,prefix+s+suffix);text.value=v.slice(0,a)+prefix+s+suffix+v.slice(b);text.setSelectionRange(a+prefix.length,a+prefix.length+s.length);}';
        $html .= 'function block(prefix){var v=text.value,a=text.selectionStart,b=text.selectionEnd,start=a;while(start>0&&v.charAt(start-1)!="\n")start--;var end=b;while(end<v.length&&v.charAt(end)!="\n")end++;var s=v.slice(start,end);if(s.slice(0,prefix.length)===prefix)s=s.split("\n").map(function(x){return x.slice(prefix.length);}).join("\n");else s=s.split("\n").map(function(x){return prefix+x;}).join("\n");text.value=v.slice(0,start)+s+v.slice(end);text.focus();text.setSelectionRange(start,start+s.length);}';
        $html .= 'function link(){var url=window.prompt("URL:","https://");if(url===null)return;var a=text.selectionStart,b=text.selectionEnd,v=text.value,s=v.slice(a,b);var ins=s?"["+s+"]("+url+")":"[link]("+url+")";text.value=v.slice(0,a)+ins+v.slice(b);text.focus();text.setSelectionRange(a+ins.length,a+ins.length);}function format(){var p=window.prompt("Format:","h2");if(p==="h1"||p==="h2"||p==="h3")block(p==="h1"?"# ":p==="h2"?"## ":"### ");}';
        $html .= 'function togglePreview(){if(!preview.hasAttribute("hidden")){preview.hidden=true;text.hidden=false;return;}var payload=new FormData();payload.append("action","preview");payload.append("yellowcsrftoken",document.querySelector("input[name=yellowcsrftoken]").value);payload.append("rawdataedit",text.value);payload.append("rawdataendofline",document.querySelector("input[name=rawdataendofline]").value);var xhr=new XMLHttpRequest();xhr.open("POST",window.location.pathname,true);xhr.onload=function(){if(xhr.status===200){preview.innerHTML=xhr.responseText;text.hidden=true;preview.hidden=false;}};xhr.send(payload);}';
        $html .= 'document.querySelectorAll("[data-section-action]").forEach(function(el){el.addEventListener("click",function(e){e.preventDefault();var a=el.getAttribute("data-section-action");if(a==="bold")wrap("**","**");else if(a==="italic")wrap("*","*");else if(a==="strikethrough")wrap("~~","~~");else if(a==="code")wrap("`","`");else if(a==="list")block("* ");else if(a==="link")link();else if(a==="format")format();else if(a==="preview")togglePreview();else if(a==="save")form.submit();});});focusText();})();</script></body></html>';
        return $this->yellow->sendData(200, array("Content-Type" => "text/html; charset=UTF-8", "Cache-Control" => "no-cache, no-store"), $html);
    }
}
