<?php
trait YellowSectioneditPart4 {
function getSectionAnchor($rawData, $sectionId) { $sections = $this->scan($rawData); $target = $this->findSection($sections, $sectionId); if (!$target) return ""; $anchor = $this->yellow->lookup->normaliseName($target["title"], true, false, true); if (is_string_empty($anchor)) return ""; $count = 0; foreach ($sections as $section) { if ($this->yellow->lookup->normaliseName($section["title"], true, false, true) === $anchor) { $count++; if ($section["id"] === $sectionId) break; } } return $count === 1 ? $anchor : ""; }
function findSection($sections, $id) { foreach ($sections as $section) { if ($section["id"] === $id) return $section; } return null; }
function showFileDiagnostic($location, $fileName) { $contentFile = $this->yellow->lookup->isContentFile($fileName); $readable = !is_string_empty($fileName); $html = $this->diagnosticStart("SectionEdit 0.1.14 - file diagnostic"); $html .= '<h1>SectionEdit: file could not be resolved</h1><dl>'; $html .= $this->diagnosticRow("Location", $location); $html .= $this->diagnosticRow("File", $fileName); $html .= $this->diagnosticRow("Content file", $contentFile ? "yes" : "no"); $html .= $this->diagnosticRow("Readable", $readable ? "yes" : "no"); $html .= '</dl><p>The normal Yellow request lookup produced the values above. This diagnostic replaces the generic 404 page for SectionEdit testing.</p>'; $html .= $this->diagnosticEnd(); return $this->yellow->sendData(404, array("Content-Type" => "text/html; charset=UTF-8"), $html); }
function showSectionDiagnostic($location, $fileName, $sectionId, $sections, $base) { $html = $this->diagnosticStart("SectionEdit 0.1.14 - section diagnostic"); $html .= '<h1>SectionEdit: section not found</h1>'; $html .= $this->diagnosticRow("Requested section", $sectionId === "" ? "(empty/invalid)" : $sectionId); $html .= $this->diagnosticRow("Location", $location); $html .= $this->diagnosticRow("File", $fileName); $html .= $this->diagnosticRow("Base", $base); $html .= $this->diagnosticRow("Core server base", $this->yellow->system->get("coreServerBase")); $html .= $this->diagnosticRow("Edit location", $this->yellow->system->get("editLocation")); $html .= $this->diagnosticRow("Readable", "readFile() was successful"); if (!$sections) { $html .= '<h2>No headings detected</h2><p>The scanner did not find any ATX or Setext headings outside fenced code blocks/front matter.</p>'; } else { $html .= '<h2>Detected sections</h2><table><thead><tr><th>ID</th><th>Level</th><th>Type</th><th>Title</th><th>Lines</th></tr></thead><tbody>'; foreach ($sections as $section) { $html .= '<tr><td><code>' . htmlspecialchars($section["id"], ENT_QUOTES, "UTF-8") . '</code></td><td>' . (int)$section["level"] . '</td><td>' . htmlspecialchars($section["type"], ENT_QUOTES, "UTF-8") . '</td><td>' . htmlspecialchars($section["title"], ENT_QUOTES, "UTF-8") . '</td><td>' . ((int)$section["startLine"] + 1) . '-' . (int)$section["endLine"] . '</td></tr>'; } $html .= '</tbody></table><p>Try one of the IDs above as <code>?section=...</code>.</p>'; } $html .= $this->diagnosticEnd(); return $this->yellow->sendData(404, array("Content-Type" => "text/html; charset=UTF-8"), $html); }
function diagnosticRow($label, $value) { return '<dt>' . htmlspecialchars($label, ENT_QUOTES, "UTF-8") . '</dt><dd><code>' . htmlspecialchars((string)$value, ENT_QUOTES, "UTF-8") . '</code></dd>'; }
function diagnosticStart($title) { return '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>' . htmlspecialchars($title, ENT_QUOTES, "UTF-8") . '</title><style>.diag{max-width:1100px;margin:30px auto;padding:0 20px;font:16px system-ui,sans-serif}.diag h1{margin-bottom:20px}.diag dl{display:grid;grid-template-columns:160px 1fr;gap:8px 16px}.diag dt{font-weight:600}.diag dd{margin:0;overflow-wrap:anywhere}.diag table{border-collapse:collapse;width:100%;margin-top:12px}.diag th,.diag td{border:1px solid #bbb;padding:6px 8px;text-align:left;vertical-align:top}.diag code{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}</style></head><body><main class="diag">'; }
function diagnosticEnd() { return '</main></body></html>'; }
}
